spring:
  application:
    name: PersonService
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
app:
  message: Person Service - Version Final V2 depuis GitHub
  version: 7.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

